name: My Github Workflow

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs-1:
  name: My Action
inputs:
  input1:
    required: true
  input2:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "Input 1: ${{ inputs.input1 }}"
        echo "Input 2: ${{ inputs.input2 }}"


jobs:
  my-job1:
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v4
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'
    - run: python python-file/main.py