name: My Github Workflow

on:
  push:
    branches: ["master"]

  workflow_dispatch:

    inputs:
      name:
        description: 'Person to greet'
        defaullt: 'world'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      # uses: actions/checkout@v3

      name: send greeting
      run: echo "hello ${{ github.events.name}}"

      # name: Run multii-line script
      # run: |
      #   echo ad other actions to build,
      #   echo test, and deploy our project. 
  

# jobs:
#   my-job1:
#     runs-on: windows-latest

#     steps:
#     - uses: actions/setup-python@v4
#     - uses: actions/checkout@v3
#       with:
#         python-version: '3.10'
#     - run: python python-file/main.py