name: My Github Workflow -1

on:
  push:
    branches: ["master"]

  workflow_dispatch:
    inputs:

      boolean:
        type: boolean
        description: True or False
        # description: False

      choice:
        type: choice
        description: Make a choice
        options:
        - AWS
        - AZURE
        - NEWRALIC

      first-input: 
        description: "First input"
        required: true

      second-input: 
          description: "Second input"
          required: true

env:
  file: python-file/index.py
  file1: python-file/main.py

  first-input: ${{github.event.inputs.first-input}}
  second-input: ${{github.event.inputs.second-input}}

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2

      - name: Run a one-line script
        run: python $file $first-input

      - name: Run a multi-line script
        run: echo $msg

  job2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      
      - name: Run a second-line script
        run: |
          python $file1 $second-input

  job3:
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v4
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'
    - run: python python-file/main.py

  job4:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python python-file/main.py        

