name: My Github Workflow

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  my-job1:
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v4
    - uses: actions/checkout@v3
      with:
        python-version: '3.10'

       - name: Prompt user for input
  run: |
    read -p "Enter your input: " userInput
    echo "User input was: $userInput"
  env:
    USER_INPUT: ${{ env.userInput }} 
    - run: python python-file/main.py