name: My Github Workflow

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  my-job1:
    runs-on: windows-latest

    steps:
    - uses: actions/setup-python@v4
    - name: pitambar
      uses: my-action
      with:
      input1: 'value1'
      input1: 'value2'

        python-version: '3.10'
    - run: python python-file/main.py